const QUESTIONS = [
  "What is your favorite food?",
  "What is something you are really good at?",
  "What is your dream vacation destination?",
  "What did you want to be when you grew up?",
  "What is your hidden talent?",
  "How many cups of coffee or tea do you drink per day?",
  "What is your most-used emoji?",
  "What is your go-to karaoke song?",
  "What is the weirdest food you actually enjoy?",
  "What is your favorite movie or TV show?",
  "What's a skill you'd love to learn?",
  "What's your go-to comfort activity?",
  "What's the best advice you've ever received?",
  "What's your guilty pleasure?",
  "What's a hobby you've picked up recently?",
  "What's your favorite way to spend a lazy Sunday?",
  "What's the most interesting thing in your room right now?",
  "What's your favorite type of cuisine?",
  "What's a bucket list item you're determined to cross off?",
  "What's your spirit animal and why?",
  "If you could have any superpower, what would it be?",
  "What's your most controversial opinion?",
  "What's the best compliment you've ever received?",
  "What's your favorite way to get exercise?",
  "What's a song you can't stop listening to?",
  "If you could travel anywhere right now, where would it be?",
  "What's your favorite type of weather?",
  "What's the most daring thing you've ever done?",
  "What's your go-to snack?",
  "What's a skill you're surprisingly good at?",
  "If you could have dinner with anyone, who would it be?",
  "What's your biggest pet peeve?",
  "What's your favorite book or author?",
  "What's the best vacation you've ever taken?",
  "What's your lucky number or color?",
  "What's a gift you'd love to receive?",
  "What's your favorite childhood memory?",
  "What's the most interesting job you've ever had?",
  "What's your go-to mode of transportation?",
  "What's a goal you're working toward?",
  "If you could live in any era, which would it be?",
  "What's your favorite season and why?",
  "What's the coolest thing someone has ever done for you?",
  "What's your favorite type of music?",
  "If you could master any skill instantly, what would it be?",
  "What's your proudest achievement?",
  "What's your favorite way to relax?",
  "What's the best deal you've ever found?",
  "What's your favorite word?",
  "What's your morning routine like?",
  "If you could change one thing about yourself, what would it be?",
  "What's your favorite breakfast food?",
  "What's the funniest thing that's ever happened to you?",
  "What's your ideal weekend look like?",
  "What's a class or workshop you'd love to take?",
  "What's your favorite type of dessert?",
  "What's the best advice you'd give to your younger self?",
  "What's your favorite board game or video game?",
  "What's something you're secretly proud of?",
  "What's your favorite city you've visited?"
];

module.exports = QUESTIONS;
